### ISSUE TITLE
Custom icons and `mkdocs serve` (rebuild) behavior

### ISSUE THREAD

**Issue by hemp** [facelessuser/mkdocs-material-extensions#10]
First, thanks for the custom icon set support! 

Writing down what I'm experiencing using a custom icon directory with mkdocs-material 5.2.2 docker's image.

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - custom_theme/my_icons
```

I'm noticing that rebuilds get longer each during `mkdocs serve` with a custom icon set.  `_patch_index` is called for each markdown file I think.  I started modifying the docker image's emojy.py and found a workaround but not sure the ideal fix.

Workaround:

```bash
docker run -it -v ${PWD}:/docs -v ${PWD}/deploy/dist:/docs/site --entrypoint /bin/sh squidfunk/mkdocs-material:5.2.2
```

```python
PATCHED_INDEX = None

def _patch_index(options):
    """Patch the given index."""
    global PATCHED_INDEX
    if PATCHED_INDEX is not None:
        return PATCHED_INDEX
...
    # Before return
    PATCHED_INDEX = index
```

I think the append keeps adding RESOURCES for each call of _patch_index.  Then the globbing grows over time.  Another option would be to copy the `options.get('custom_icons', []).copy()` instead of workaround above.

https://github.com/facelessuser/mkdocs-material-extensions/blob/master/materialx/emoji.py#L32
