### ISSUE TITLE
[Feature request] host emoji's with site

### ISSUE THREAD

**Issue by jon-nfc** [facelessuser/mkdocs-material-extensions#17]
Is it possible to have a feature where instead of having an external CDN provide the emoji icons, that they could be downloaded during the mkdocs build stage to be hosted along with the site that was built.

This feature would be a valuable one in relation to privacy. As the user browsing the site would not be contacting a third party. The theme provided icons are a good example of being provided by the same host as the site.

Currently I use the material theme and haven't deployed it yet due to emoji's being provided by a third party and therefore a privacy concern.

Idea for config (add a `.to_local` to the generator)
``` yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_local
```

Possible workflow
- as the site is being built by mkdocs, every emoji found is downloaded to `assets/emoji/{provider}/{emoji_name}.svg`
- the the CDN URL would be set to a reletive link to the emoji folder. If not a relative link, use `site_name` from config and append the emoji path.
- preference would be to download instead of imbed as this enables browser caching to be utilised.

Have looked at the licence of twemoji, my proposal doesn't create any issues there.

**Comment by facelessuser** [comment]
While I understand the desire to not access 3rd party sites, the underlying emoji extension (which is maintained under [pymdown-extensions](https://github.com/facelessuser/pymdown-extensions) -- which I also maintain) has chosen not to download the Twemoji images by default. With that said, just as is done here in this Material repo, we can provide our own methods if desired. This is done such that users can implement whatever they need above and beyond the defaults without me having to implement every use case that a user would desire. This saves me from having to implement and maintain custom implementations for everyone. This Material specific repo is an exception.

Essentially, support of Twemoji via the CDN is a design decision that was consciously made, with the realization of pros and cons.

With all of that said, you can actually accomplish what you want without having to implement your own functions. You can simply download the [twemoji repo](https://github.com/twitter/twemoji/tree/master/assets/svg) to your project and point to your local directory as mentioned in the[ project's readme](https://github.com/facelessuser/mkdocs-material-extensions#using-local-custom-icons):

```yml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - theme/my_icons
```

The one downside is that you will have to reference the icons by their name in that folder, and Twemoji uses Unicode codes to name their files. If you wanted friendly names, you'd have to have special emoji functions that create the appropriate database to bridge that gap, or rename the files in a way that makes sense for you as you download them (maybe limiting downloads to the most commonly used images). There are probably various ways you could accomplish what you want.

Anyways, yes this is possible to do, but I currently do not have intentions to implement such a function myself at this time as I do feel that the current solution satisfies the majority of people. My intention was always to provide a default that works for the majority of people out of the box, but empower people to create whatever they need for themselves if required.
